# This is a basic workflow to help you get started with Actions

name: CI

name: Maven Package

on:
  push:
    branches:
     - main

- name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
    - name: Transition issue
      id: transition
      uses: atlassian/gajira-transition@master
      with:
        issue: GA-1
        transition: "In progress"
